services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
    networks:
      - rabbitmq

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
  rabbitmq:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  rabbitmq:

