
server:
  port: 8082
  servlet:
    context-path: /pagamento

spring:
  application:
    name: pagamento
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/pagamento
    username: postgres
    password: postgres

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

crud:
  rabbitmq:
    exchange: crud.exchange
    queue: crud.produto.queue

security:
  jwt:
    token:
      secret-key: chave_microservices
      expire-length: 360000